/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.pe.ordermanagement.infrastructure.controller.api;

import com.pe.ordermanagement.infrastructure.dto.CreateOrderRequest;
import com.pe.ordermanagement.infrastructure.dto.ErrorResponse;
import com.pe.ordermanagement.infrastructure.dto.OrderResponse;
import com.pe.ordermanagement.infrastructure.dto.PaginatedOrdersResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.time.LocalDate;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-06-28T12:55:02.977013200-05:00[America/Lima]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "orders", description = "the orders API")
public interface OrdersApi {

    /**
     * DELETE /orders/{id} : Cancel Order by ID
     *
     * @param id  (required)
     * @return Order Cancelled (status code 204)
     *         or Order Not Found (status code 404)
     */
    @Operation(
        operationId = "cancelOrder",
        summary = "Cancel Order by ID",
        responses = {
            @ApiResponse(responseCode = "204", description = "Order Cancelled"),
            @ApiResponse(responseCode = "404", description = "Order Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/orders/{id}",
        produces = { "application/json" }
    )
    
    Mono<ResponseEntity<Void>> cancelOrder(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    /**
     * POST /orders : Create a new order
     *
     * @param createOrderRequest Inventory item to add (required)
     * @return Orden creada (status code 201)
     *         or Invalid input (status code 400)
     */
    @Operation(
        operationId = "createOrder",
        summary = "Create a new order",
        responses = {
            @ApiResponse(responseCode = "201", description = "Orden creada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OrderResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/orders",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    Mono<ResponseEntity<OrderResponse>> createOrder(
        @Parameter(name = "CreateOrderRequest", description = "Inventory item to add", required = true) @Valid @RequestBody Mono<CreateOrderRequest> createOrderRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    /**
     * GET /orders/{id} : Get Order by ID
     *
     * @param id  (required)
     * @return Order Details (status code 200)
     *         or Order Not Found (status code 404)
     */
    @Operation(
        operationId = "getOrderById",
        summary = "Get Order by ID",
        responses = {
            @ApiResponse(responseCode = "200", description = "Order Details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OrderResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Order Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/orders/{id}",
        produces = { "application/json" }
    )
    
    Mono<ResponseEntity<OrderResponse>> getOrderById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    /**
     * GET /orders : Get all orders
     *
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @param status  (optional, default to CREATED)
     * @param fromDate  (optional)
     * @param toDate  (optional)
     * @return Order List (status code 200)
     */
    @Operation(
        operationId = "listOrders",
        summary = "Get all orders",
        responses = {
            @ApiResponse(responseCode = "200", description = "Order List", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = PaginatedOrdersResponse.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/orders",
        produces = { "application/json" }
    )
    
    Mono<ResponseEntity<Flux<PaginatedOrdersResponse>>> listOrders(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "10") Integer size,
        @Parameter(name = "status", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "status", required = false, defaultValue = "CREATED") String status,
        @Parameter(name = "fromDate", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "fromDate", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate fromDate,
        @Parameter(name = "toDate", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "toDate", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate toDate,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
